version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  postgres:
    container_name: sb-postgres
    image: postgres:9.6
    # Problems next major versions 10, 11 and 1 with Doctrine
    # an exception occurred in driver: SQLSTATE[08006] [7] FATAL:  unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0
    # SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
    ports:
      - "5434:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db